sudo: false
language: android
jdk: oraclejdk7

android:
    components:
        - platform-tools
        - tools
        - android-23
        - build-tools-23.0.0
        - extra-android-support
    licenses:
        - android-sdk-license-5be876d5
script:
    - make test
